[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
events_sol1 = "9vhSousnsM3zDPwhL4QUef5tsrRZBaQjdopaw8WZmDp4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/merlin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
